sonar.projectKey=final-testing
sonar.sources=src
sonar.host.url=http://172.17.0.1:9010
sonar.token=sqp_44f9c3a917c46aa9534b24d996cb52229713737b
sonar.exclusions=node_modules/**

#Run this command for running sonarqube scanner with docker
#docker run --rm   -e SONAR_HOST_URL=http://172.17.0.1.9010   -v "$(pwd):/usr/src"   sonarsource/sonar-scanner-cli

